var names = [
    'Marcel Van strien',
    'silvia schuiling',
    'Bernardo Loesberg',
    'Jerry de Swart',
    'Jeroen van den Bergh',
    'E. Malenstein',
    'Will Falk-Wildschut',
    'Jos Slangen',
    'Cees en Tineke van Tiel',
    'Roald Bosch',
    'Carianne Heikoop – Berrevoets',
    'Joop Hendriks',
    'Richard Honselaar',
    'Sabrina Koemans',
    'Lia Straver',
    'Eric en Nel Jochems',
    'Mevr. van Koolwijk',
    'Camping De Warme Bossen',
    'Jan van Elst',
    'Corrie Smit-Kroon',
    'Arend van Breda',
    'ina kromeich',
    'Monique Rijnenberg',
    'G swart',
    'Hans Verleun',
    'Minko Balt',
    'Mandy Bruggink',
    'Anja Franken',
    'Carl en Jo Schneider',
    'jack scheltema',
    'L v.Duijn  de Waard',
    'Joke Kooijman van den Berg',
    'Marinus van der Weele',
    'Lieke Dielissen',
    'Margreet Frieling – Beuving',
    'wiebrand van de Beld',
    'Naomi Geervliet',
    'Fred Groenen',
    'Dave Baas',
    'Ria Both',
    'monique wissink',
    'Petra Kuiper',
    'Hans Van Oosten',
    'Betty Semler',
    'Marije en Vincent',
    'Rosalie Mulder',
    'Martin leeuw',
    'WillyAn Hillebrand',
    'Erica Westendorp',
    'marlies blijleven',
    'MariJan Driessen Rutten',
    'E van Lent'
]

var rand = () => {
    // if ( Math.random() < .2 ) return 'Dank je wel';
    return names[ Math.floor( Math.random() * ( names.length - 1 ) ) ];
}

rand.list = names;

module.exports = rand;var names = [
    'Marcel Van strien',
    'silvia schuiling',
    'Bernardo Loesberg',
    'Jerry de Swart',
    'Bernardo Loesberg',
    'Jeroen van den Bergh',
    'E. Malenstein',
    'Will Falk-Wildschut',
    'Jos Slangen',
    'Cees en Tineke van Tiel',
    'Roald Bosch',
    'Carianne Heikoop – Berrevoets',
    'Joop Hendriks',
    'Richard Honselaar',
    'Sabrina Koemans',
    'Lia Straver',
    'Eric en Nel Jochems',
    'Mevr. van Koolwijk',
    'Camping De Warme Bossen',
    'Jan van Elst',
    'Corrie Smit-Kroon',
    'Arend van Breda',
    'ina kromeich',
    'Monique Rijnenberg',
    'G swart',
    'Hans Verleun',
    'Minko Balt',
    'Mandy Bruggink',
    'Anja Franken',
    'Carl en Jo Schneider',
    'jack scheltema',
    'L v.Duijn  de Waard',
    'Joke Kooijman van den Berg',
    'Marinus van der Weele',
    'Lieke Dielissen',
    'Margreet Frieling – Beuving',
    'wiebrand van de Beld',
    'Naomi Geervliet',
    'Fred Groenen',
    'Dave Baas',
    'Ria Both',
    'monique wissink',
    'Petra Kuiper',
    'Hans Van Oosten',
    'Betty Semler',
    'Marije en Vincent',
    'Rosalie Mulder',
    'Martin leeuw',
    'WillyAn Hillebrand',
    'Erica Westendorp',
    'marlies blijleven',
    'MariJan Driessen Rutten',
    'E van Lent'
]

var rand = () => {
    // if ( Math.random() < .2 ) return 'Dank je wel';
    return names[ Math.floor( Math.random() * ( names.length - 1 ) ) ];
}

rand.list = names;

module.exports = rand;